style_share_2/config/routes.rb
Rails.application.routes.draw do
  resources :prompts
  get "style_share_2/app/views/prompts/show.html.erb", to: "pages#show", as: "user_prompt"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#show'
  get 'pages/show'
  post 'pages/show', to: 'pages#update'

  resources :sketches
end

style_share_2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

style_share_2/app/models/prompt.rb
class Prompt < ApplicationRecord
    has_one_attached :image
end

style_share_2/app/models/sketch.rb
class Sketch < ApplicationRecord
end

style_share_2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

style_share_2/app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def show
    @width ||= 800
    @height ||= 600
  end

  def update
    @size = params[:resolution]
    case @size[:res_string]
    when "640x480"
      @width = 640
      @height = 480
    when "800x600"
      @width = 800
      @height = 600
    when "1024x768"
      @width = 1024
      @height = 768
    end
    render :show
  end

  def user_prompt

  end
  #
  # private

    # def set_sketch
    #   @sketch = Sketch.find(params[:id])
    # end
    #
    # def sketch_params
    #   params.require(:sketch).permit(:title, :description, :code)
    # end
    #
    # def user_prompt_params
    #   params.require(:prompt).permit(:title, :image)
    # end

  end

style_share_2/app/controllers/prompts_controller.rb
class PromptsController < ApplicationController
  before_action :set_prompt, only: [:show, :edit, :update, :destroy]

  # GET /prompts
  # GET /prompts.json
  def index
    @prompt = Prompt.all
  end

  # GET /prompts/1
  # GET /prompts/1.json
  def show
      @prompt = Prompt.find(params[:id])
  end

  # GET /prompts/new
  def new
    @prompt = Prompt.new
  end

  # GET /prompts/1/edit
  def edit
      @prompt = Prompt.find(params[:id])
  end

  # POST /prompts
  # POST /prompts.json
  def create
    @prompt = Prompt.new(prompt_params)

    respond_to do |format|
      if @prompt.save
        format.html { redirect_to @prompt, notice: 'Prompt was successfully created.' }
        format.json { render :show, status: :created, location: @prompt }
      else
        format.html { render :new }
        format.json { render json: @prompt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prompts/1
  # PATCH/PUT /prompts/1.json
  def update
    respond_to do |format|
      if @prompt.update(prompt_params)
        format.html { redirect_to @prompt, notice: 'Prompt was successfully updated.' }
        format.json { render :show, status: :ok, location: @prompt }
      else
        format.html { render :edit }
        format.json { render json: @prompt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prompts/1
  # DELETE /prompts/1.json
  def destroy
    @prompt.destroy
    respond_to do |format|
      format.html { redirect_to prompts_url, notice: 'Prompt was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # def set_prompt
    #   @prompt = Prompt.find(params[:id])
    # end

    # Only allow a list of trusted parameters through.
    def prompt_params
      params.require(:prompt).permit(:image)
    end
end

style_share_2/app/controllers/sketches_controller.rb
class SketchesController < ApplicationController
  before_action :set_sketch, only: [:show, :edit, :update, :destroy]

  def index
    @sketches = Sketch.all
  end

  def show
  end

  def create
    @sketch = Sketch.new(sketch_params)
    @sketch.code = @sketch.code.strip
    if @sketch.save
      redirect_to @sketch
    else
      render :new
    end
  end

  def new
    @sketch = Sketch.new
  end

  def edit
  end

  def update
    if @sketch.update(sketch_params)
      redirect_to @sketch
    else
      render :edit
    end
  end

  def destroy
    @sketch.destroy
    redirect_to sketches_url
  end

  private

    def set_sketch
      @sketch = Sketch.find(params[:id])
    end

    def sketch_params
      params.require(:sketch).permit(:title, :description, :code)
    end

    def prompt_params
      params.require(:prompt).permit(:title, :image)
    end

end

style_share_2/app/helpers/application_helper.rb
module ApplicationHelper
end

style_share_2/app/helpers/prompts_helper.rb
module PromptsHelper
end

style_share_2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StyleShare</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'p5' %>
    
    <script
    src="https://code.jquery.com/jquery-3.4.1.min.js"
      integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <!-- <script src="https://cdn.jsdelivr.net/npm/p5@1.0.0/lib/p5.js"></script> -->
  </head>

  <body>
      <section id="navbar">
      <div class="navbar-top">
        <div class="navbar area">
           <h1><%= link_to "StyleShare", sketches_path %></h1>
        </div>
        <div class="navbar-links" id="navigation">
          <ul>
            <li><%= link_to "Sample Sketch", root_path %></li>
          </ul>
          <button data-collapse data-target="#navigation" class="toggle" <span class="icon"></span></button>
        </div>
      </div>
    </section>

    <section class="main-container">
        <%= yield %>
    </section>
    <!-- <script>
        points = [];
        begin = false;
        console.log($("#navbar"));
        function setup() {
            let canvas = createCanvas(<%= @width %>,<%= @height %>).parent("#p5canvas");
            $("#canvas-size").text(width + "x" + height);

            background(255,255,255);
        }

        function draw(){


            if(begin){
                points.push(createVector(mouseX, mouseY));
        }

        stroke(0,0,0);
        noFill();
        beginShape();
        for(let i = 0; i < points.length; i++){
            let x = points[i].x;
            let y = points[i].y;

            vertex(x, y);
        }
            endShape();
        }

        function mousePressed(){
            begin = true;
            points = [];
        }

        function mouseReleased(){
            start = false;
        }
    </script> -->
  </body>
</html>

style_share_2/app/views/pages/_canvas_model.html.erb
<div class="center-div">

    <h2>Enter Your Prompt Pic:</h2>

    <div class="sketch-form">
    <%= form_for :resolution, url: pages_show_path do |form| %>
    <%= form.file_field :image %>
    <%# <%= render :partial => 'prompts/form' %>
    <% end %>
    </div>


    <h2>Your Canvas</h2>

    <%= form_for :resolution, url: pages_show_path do |f| %>
    <%= f.select :res_string, options_for_select([["1024x768"],["800x600"],["640x480"]]) %>
    <%= f.submit "Change" %>
    <% end %>

    <p id="canvas-size"></p>
    <div id="p5canvas">
    </div>

</div>

<%= render 'user_canvas' %>

style_share_2/app/views/pages/_user_canvas.html.erb
<script>
    points = [];
    begin = false;
    console.log($("#navbar"));
    function setup(){
        let canvas = createCanvas(<%= @width %>,<%= @height %>).parent("#p5canvas");
        $("#canvas-size").text(width + "x" + height);

        background(255,255,255);
    }

    function draw() {

        if(begin){
            points.push(createVector(mouseX, mouseY));
        }

    stroke(0,0,0);
    noFill();
    beginShape();
    for(let i = 0; i < points.length; i++){
        let x = points[i].x;
        let y = points[i].y;

        vertex(x, y);
    }
        endShape();
    }

    function mousePressed(){
        begin = true;
        points = [];
    }

    function mouseReleased(){
        begin = false;
    }
</script>

style_share_2/app/views/pages/show.html.erb
<%= render 'canvas_model' %>

style_share_2/app/views/prompts/_form.html.erb
<%= form_for(@prompt) do |form| %>

  <div class="sketch-form">
      <%= form.label :image %>
      <%= form.file_field :image %>
  </div>

  <div style="width: 640px; height: auto">
      <%= image_tag(@prompt.image, style: "width: 100%") %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

style_share_2/app/views/prompts/edit.html.erb
<h1>Editing Prompt</h1>

<%= render 'form', prompt: @prompt %>

<%= link_to 'Show', @prompt %> |
<%= link_to 'Back', prompts_path %>

style_share_2/app/views/prompts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Prompts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prompts.each do |prompt| %>
      <tr>
        <td><%= prompt.title %></td>
        <td><%= link_to 'Show', prompt %></td>
        <td><%= link_to 'Edit', edit_prompt_path(prompt) %></td>
        <td><%= link_to 'Destroy', prompt, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Prompt', new_prompt_path %>

style_share_2/app/views/prompts/new.html.erb
<h1>New Prompt</h1>

<%= render 'form', prompt: @prompt %>

<%= link_to 'Back', prompts_path %>

style_share_2/app/views/prompts/show.html.erb
<p id="notice"><%= notice %></p>

<div style="width: 640px; height: auto">
    <%= image_tag(@prompt.image, style: "width: 100%") %>
</div>

<%= render partial: 'user-prompt' %>

style_share_2/app/views/sketches/_form.html.erb
<%= form_for(sketch) do |f| %>

    <div class="sketch-form">
        <ul>
            <li>
                <%= f.label :artist %>
                <%= f.text_field :artist %>
            </li>
            <li>
                <%= f.label :description %>
                <%= f.text_field :description %>
            </li>
            <li>
                <%= f.label :code %>
                <%= f.text_area :code %>
            </li>
            <li>
                <%= f.button %>
            </li>
        </ul>

    </div>
<% end %>

style_share_2/app/views/sketches/_sketch.html.erb
<div class="rounded-box inline">
    <div class="sketch-info">
        <ul>
            <li>
                <p class="sketch-artist"><%= sketch.artist %></p>
            </li>
            <li>
                <p>Description:</p>
                <small><%= sketch.description %></small>
            </li>
        </ul>
    </div>
    <br>
    <div class="links-bottom">
        <small><%= link_to "Open", sketch %></small>
        <small><%= link_to "Edit", edit_sketch_path(sketch) %></small>
        <small><%= link_to "Delete", sketch, method: :delete %></small>
    </div>
</div>

style_share_2/app/views/sketches/edit.html.erb
<div class="container">

    <h3>Edit Sketch</h3>

    <%= render 'form', sketch: @sketch %>
</div>

style_share_2/app/views/sketches/index.html.erb
<div class="container">
    <h3>Sketch List</h3>

    <%= render @sketches %>

    <br>
    <hr>

    <div class="main-link">
        <%= link_to "New Sketch", new_sketch_path %>
    </div>

</div>

style_share_2/app/views/sketches/new.html.erb
<div class="center-div">

    <h3>New Sketch</h3>

    <div class="form-container">
        <%= render 'form', sketch: @sketch %>
    </div>

</div>

style_share_2/app/views/sketches/show.html.erb
<div class="container">

    <h3><%= @sketch.artist %></h3>

    <small><%= @sketch.description %></small>

    <div class="box-code">
        <%= @sketch.code.html_safe %>
    </div>

    <br>
    <div id="sketch-canvas">
        <script>
            <%= (@sketch.code).html_safe %>
        </script>
    </div>
    <br>

    <small><%= link_to "Edit", edit_sketch_path(@sketch) %></small>
    <small><%= link_to "Delete", @sketch, method: :delete %></small>

</div>